### ISSUE TITLE
Ideas for models for the GC paper

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#100]
- [x] Alarm example (external, used in the "Validated Designs for Object-oriented Systems" book)
  - Generate large amounts of internal data
- [x] CashDispenser (external, developed in connection with FM'99)
   - Recursion
   - Big model
- [x] Pacemaker (external, used in the "Validated Designs for Object-oriented Systems" book)
  - Uses maps and sets
  - Easy to define entry points that generate large amounts of data (see comments below).
- [x] Bubble sort
   - Iterative
   - Generates lots of internal data
   - Focuses on execution time

**Comment by peterwvj** [comment]
I thought about using the Pacemaker model, from the "Validated Designs for Object-oriented Systems" book (just like the Alarm example). That model ships with Overture and is called PacemakerSimplePP. Although the pacemaker model is not very big it does makes use set and sequence operations. Another nice thing about that model is that it is easy to define entry points that produce large collection values. For example by passing a large heart trace sequence to the `Pace` operation: `new Pacemaker().Pace(heartTrace,5,2)`.

**Comment by peterwvj** [comment]
I added a VDMPP version of the bubble sort algorithm. Intended use is shown below.

<details>
  <summary>Intended use</summary>

```
class BubbleSortTesting is subclass of TestCase

operations

public test_Worstcase : () ==> ()
test_Worstcase () == runSort([10,9,8,7,6,5,4,3,2,1],[1,2,3,4,5,6,7,8,9,10]);  

public test_Mixed : () ==> ()
test_Mixed () == runSort([5,3,9,7,1,8], [1,3,5,7,8, 9	]);


private runSort : (seq of int) * (seq of int) ==> ()
runSort (input, expected) ==
let algo = new BubbleSort(input)
in
(
  algo.sort();
  let actual = algo.getNumbers()
  in 
    Assert`assertTrue("Expected " ^ VDMUtil`val2seq_of_char[seq of int](input) ^ " to be sorted as " ^ VDMUtil`val2seq_of_char[seq of int](expected) ^ " but got: " ^ VDMUtil`val2seq_of_char[seq of int](actual) ^ ".", actual = expected);
);

public runFullSuite : () ==> ()
runFullSuite () == 
let	 ts: TestSuite = new TestSuite(self),
     result = new TestResult()
in
(
  ts.run(result);
  IO`print(result.toString());
);

end BubbleSortTesting
```
</details>

**Comment by peterwvj** [comment]
The `PaperExampleTests` has been update to check that all the paper examples code-generate/compile without any problems.

**Comment by bandurvp** [comment]
Hi Peter,

As we evolve these example models for the purpose of the paper, do you want to do this in the examples directory?  So for example, my test and validation plans for the alarm example I currently have in SVN, but I could move it over to the VDM2C repository.  Was this what you had in mind?

Victor

**Comment by peterwvj** [comment]
Hi @bandurvp . If we keep the test code in the SVN repository then let's just maintain the models + the test/validation plans there. Would you be OK with that?

**Comment by peterwvj** [comment]
Currently, for the CashDispenser model, it takes much longer for the VDM2C-generated code to complete (stress test 1). We need to investigate why that is.

**Comment by bandurvp** [comment]
It turns out that once you compile the sources with the ```-pg``` option and run the executable once just by itself, it generates a file called ```gmon.out```.  This is then picked up and used automatically when you run the executable through ```gperf```.
