### ISSUE TITLE
Emit default constructor for records to support ASN1 work

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#102]
Because of the semantics of records, when they are generated the only constructor that is emitted is the one that takes as many arguments as there are fields in the record.  @tfabbri needs access to the default constructor for his work.  For records this should be emitted just like it is for classes, but surrounded by 
```
#ifdef ASN1SCC_MAPPING
default constructor here
#endif
```

**Comment by peterwvj** [comment]
@tfabbri Could you try out the fix?

**Comment by tfabbri** [comment]
Works like a charm!

**Comment by peterwvj** [comment]
Very good, thanks for checking!
