### ISSUE TITLE
Investigate whether numField_ field can be removed

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#104]
Currently, we generate two different fields that count the number of fields in a class. One of them is an instance field, the other one is a global field. Probably, the global field can be removed.

**Comment by bandurvp** [comment]
I suspect this was added in support of @tfabbri 's work with TASTE.  I'm waiting for him to get back to me.

**Comment by tfabbri** [comment]
Sorry for the late reply. I do not use the numField_ field  in the B_mapper of TASTE.
