### ISSUE TITLE
Sequence grow mechanism needs to be fixed

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#106]
Collections initialized using `*toGrow` functions are not expanded correctly when they need to be reallocated two or more times.  A collection needs to keep track not only of how may elements are currently in it, but how large the buffer is.  This should always be larger than or equal to the number of elements.

**Comment by peterwvj** [comment]
Sequences have been fixed, sets and maps are left to be done

**Comment by bandurvp** [comment]
Maps don't need updating for this issue because they use a different underlying storage meachanism, linked lists vs. arrays.  Actually ```NewMapVarToGrow``` is a misnomer at this point because there's no provision for growth, so we should consider renaming to just ```NewMapVar``` or something similar.

**Comment by peterwvj** [comment]
Yeah, good catch. I just renamed `newMapVarToGrow` to `newMapVar` like you suggested. Can we consider this issue closed?

**Comment by bandurvp** [comment]
Definitely.
