### ISSUE TITLE
Add the '++' operator for the VdmMap constructs

### ISSUE THREAD

**Issue by miranha** [overturetool/vdm2c#107]
Add transformation and corresponding template for the '++' operator for maps

**Comment by peterwvj** [comment]
The '++' operator is used for both map overriding and sequence modifications. Map overriding is already supported. To address this issue, the following tasks must be completed:

* Add runtime support for sequence modifications
  - [x] Explicit version
  - [x] Garbage collection version, if needed
- [x] Update the garbage collection transformation
- [x] Add integration tests
