### ISSUE TITLE
Ignore ports in hardware interface that are irrelevant to each CPU

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#115]
In code generated from distributed models, ports in `HardwareInterface` that are not relevant for a given CPU should not take up space as instances of subclasses of `Port` for that CPU.

**Comment by bandurvp** [comment]
@miranha , I think the approach we've taken with CPU-specific versions of `HardwareInterface` and deployment to relevant CPUs covers this, what do you think?

**Comment by miranha** [comment]
Yes, I believe we can close this.
