### ISSUE TITLE
Remove `ref_from` from 

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#123]
If the current GC approach is to pass `NULL` as `ref_from` then remove it from `TVP`.

**Comment by bandurvp** [comment]
@peterwvj can you confirm whether there is any situation currently where the code generator emits anything other than `NULL` as the `from` parameter to `GC` calls?

**Comment by peterwvj** [comment]
@bandurvp it should all be contained in the GC transformation yes.

**Comment by bandurvp** [comment]
Right, and in there there is no case in which it emits something like `&res` instead of `NULL`?

**Comment by peterwvj** [comment]
I'm pretty sure we got rid of all of that at one point. We only pass `NULL`.

**Comment by bandurvp** [comment]
Hi @peterwvj , I want to attempt to remove all traces of `NULL` and `ref_from` from the garbage collector if it's not used.  You said earlier that it's all in the GC transformation.  What I plan to do is to temporarily duplicate all the GC operations in the runtime but without the `from` parameter and then remove the part of the GC transformation that puts in this parameter value.  Is there anything else I should conisder?

**Comment by peterwvj** [comment]
Hi @bandurvp . I don't think there's anything else to consider, but I could be wrong.

Wouldn't it be better/safer to simply remove the "NULL parameter" from the function definitions in the runtime (rather than duplicating them).  Otherwise the approach sounds fine.

**Comment by bandurvp** [comment]
That would be the final approach, I was just thinking that this would be just a way of organizing the change.  But if I think about it there isn't really an advantage to it, thanks!  I'll let you know how things come out.  Can I merge your branch into development and branch from there?

**Comment by peterwvj** [comment]
Yes, absolutely 👌
