### ISSUE TITLE
Emit GC versions of class constructors

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#124]
Classes should emit a GC version of their constructor.   For instance, the model
```
class A
operations
public op : () ==> ()
op() ==
	let a = new A() in skip;	 
end A
```
must additionally emit the constructor
```c
TVP _Z1AEVGC(ACLASS this, TVP *from)
{
	TVP tmp = _Z1AEV(this);
	add_allocd_mem_node(tmp, from);
	return tmp;
}
```
This requires the corresponding addition to the header file of the class:
```c
TVP _Z1AEVGC(ACLASS this_, TVP *from); 
```
Also requires updating the GC transfomation to emit GC constructor calls.

**Comment by peterwvj** [comment]
@bandurvp Could you try the fix I just pushed to `pvj/development` (9e1f19d)

**Comment by bandurvp** [comment]
Hi @peterwvj , works well, but the GC versions do not get emitted in the case of calls to static operations, such as in this model:
```
class A
operations
public static sop : () ==> ()
sop() == skip;

public op : () ==> ()
op() ==  A`sop();	 
end A
```

In this case an instance of the class A is created inside the body of `op` which should be the GC version, or else should be `vdmFree`d.

**Comment by peterwvj** [comment]
Good catch, @bandurvp . Fix pushed to `pvj/development`. Could you give it a try again?
