### ISSUE TITLE
Add `newSeqVarToGrowGC` to runtime and also emit instead of `newSeqVarToGrow`

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#125]

**Comment by peterwvj** [comment]
Hi @bandurvp . I tried to update the code-generator to emit `newSeqVarToGrowGC`. But I found two problems: First, `newSeqVarToGrowGC` seems to be missing in the header file. Now, when I add it one of the tests seqfaults, and I see the following warning in the compiler output:

```
...
 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/peter/git-repos/vdm2c/c/third_party/googletest/googletest/include  -fmessage-length=0 -std=c89 -g   -o CMakeFiles/ExpressionComprehensions.dir/home/peter/git-repos/vdm2c/c/vdmclib/src/main/VdmSeq.c.o   -c /home/peter/git-repos/vdm2c/c/vdmclib/src/main/VdmSeq.c
/home/peter/git-repos/vdm2c/c/vdmclib/src/main/VdmSeq.c: In function ‘newSeqVarToGrowGC’:
/home/peter/git-repos/vdm2c/c/vdmclib/src/main/VdmSeq.c:199:12: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
  TVP res = newCollectionWithValuesPreallocGC(count, VDM_SEQ, value);
....
```

**Comment by peterwvj** [comment]
@bandurvp The commit that updates the code-generator to emit `newSeqVarToGrowGC` is in `pvj/issue-125`.

**Comment by bandurvp** [comment]
Hi @peterwvj , I've just pushed a fix for this.  It was a fairly severe problem with the scheme for growing sequences while under GC control, but one with a very simple, that is, one-line solution!  I haven't merged it into development.  I'll check whether this is a problem for sets as well, I suspect it might be.

**Comment by bandurvp** [comment]
OK I've pushed the fix for sets as well.

**Comment by peterwvj** [comment]
Cool, @bandurvp - good job. That should fix the issue in the CashDispenser model.

**Comment by bandurvp** [comment]
Haha yes it fixes that one issue... :-)
