### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#14]
While trying to get myself familiar with the development environment I noticed a few things that need to be added to the readme
- [x] It needs to mention that cmake is needed in order to run the tests
- [x] Description of test properties is outdated
- [x] Put a note saying that the googletest submodule must be initliased
- [x] Merge all "READMEs" into a single one

Requested by Tommaso
- [ ] Macros introduced for conversions
- [x] Description of TypedValue

**Comment by tfabbri** [comment]
Add to the README:
- [ ] Macros introduced for conversions
- [ ] Description of TypedValue

**Comment by peterwvj** [comment]
Since involves documentation of C code I'll assign you @bandurvp . Note that that I already reworked the README significantly (as indicated by the commits listed above), but on my own branch `pvj/test-pass`.
