### ISSUE TITLE
Expand VDM2C command-line

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#17]
For testing purposes it would be useful to expand the CLI with functionality that allows the generated code to be printed to the console

**Comment by tfabbri** [comment]
I propose also to have an interface that takes as input not only the working directory but also a single vdmpp file.

**Comment by peterwvj** [comment]
Sure that's a good suggestion. I'll update the CLI to support that.

**Comment by peterwvj** [comment]
The CLI now allows individual *VDM-RT* files to be passed to the code generator like you suggest, @tfabbri. Sample usage is shown below:

```
peter@peter-pc:~/Desktop/tmp/vdm2c
λ ls
M.vdmrt
vdm2c.jar
peter@peter-pc:~/Desktop/tmp/vdm2c
λ cat M.vdmrt 

class A
end A

class B
end B
peter@peter-pc:~/Desktop/tmp/vdm2c
λ java -jar vdm2c.jar M.vdmrt -dest out
C code generated to folder: /home/peter/Desktop/tmp/vdm2c/out
Generated file: /home/peter/Desktop/tmp/vdm2c/out/A.c
Generated file: /home/peter/Desktop/tmp/vdm2c/out/B.c
Generated file: /home/peter/Desktop/tmp/vdm2c/out/A.h
Generated file: /home/peter/Desktop/tmp/vdm2c/out/B.h
peter@peter-pc:~/Desktop/tmp/vdm2c
λ ls out/
A.c
A.h
B.c
B.h
peter@peter-pc:~/Desktop/tmp/vdm2c
λ java -jar vdm2c.jar M.vdmrt -dest out --quiet
peter@peter-pc:~/Desktop/tmp/vdm2c
λ 
```

I decided to not include the "print-to-console" feature that I originally requested. Even for the smallest model the code generator produces so much C code that it I don't find this feature helpful. Please let me know if you think otherwise.
