### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#2]
Here is a list of tasks that needs to be implemented. Please add more.
- [x] Class structure
- [x] Class structure + inheritance
- [x] Field access
  - [x] local
  - [x] public
- [x] Calls 
  - [x] local
  - [x] public
  - [x] name, 
  - [x] self, 
  - [x] new, 
  - [x] object field , 
  - [x] object apply
- [x] Memory management free all that is constructed
- [ ] expressions
  - [x] time
  - [x] set
  - [x] seq
  - [x] map
  - [ ] pattern-match
  - [x] let
    - [x] let
    - [x] let be
  - [x] def
  - [ ] conditional
    - [x] if then else
    - [ ] cases + others
  - [x] Quantified (try to rewrite these using basic constructs)
    - [x] forall
    - [x] exists
    - [x] exists1
  - [ ] iota
  - [x] mk tuple
  - [x] mk record
  - [ ] apply
    - [x] apply `()`
    - [x] field select `a.b`
    - [x] tuple select `a.#1`
    - [ ] function type instantiation (not sure what this is name[type,type] _make polymorphism_)
  - [x] new
  - [x] self
  - [ ] lambda
  - [ ] narrow?
  - [ ] is `is_...`
    - [x] bool
    - [ ] nat
    - [ ] nat1
    - [x] int
    - [ ] rat
    - [x] real
    - [ ] char
    - [ ] token
  - [ ] isofbaseclass
  - [ ] isofclass
  - [ ] samebaseclass
  - [ ] sameclass
  - [ ] undefined _this maps to nothing_
  - [ ] patterns
    - [ ] identifier
    - [ ] match
    - [ ] set enum
    - [ ] set union
    - [ ] seq enum
    - [ ] seq conc
    - [ ] map enum
    - [ ] map munion
    - [ ] tuple 
    - [ ] record
    - [ ] object
  - [x] values
- [ ] statements
  - [x] for loop _rewrite all to a while+ scope_
    - [x] sequence loop `for pattern in set SEQ do stm`
    - [x] set for loop `for all pattern in set SET do stm`
    - [x] index `for id = 1 to 10 by 2 do exp`
  - [x] while
  - [ ] nondeterministic stm `|| (stm1,stm2)`
  - [x] return
  - [x] skip
  - [x] duration \* equals skip*
  - [x] cycles _equals skip_
- [ ] Patterns + binds
  - [x] identifier
  - [ ] ...
- [ ]  number operations. All number operations must conform to the 
  
  > The five numeric types denote a subset hierarchy where real is the most general type followed
  > by rat3, int, nat and nat1. Note that no “casting” like it is done in many programming
  > languages is needed in the VDM languages.
  > This means that any number of type int is also automatically of type real but not necessarily
  > of type nat. Another way to illustrate this is to say that the positive natural numbers are a subset
  > of the natural numbers which again are a subset of the integers which again are a subset of the
  > rational numbers which finally are a subset of the real numbers. The following table shows some
  > numbers and their associated type. LangMan p. 8

This is not the case right now.

**Comment by bandurvp** [comment]
Checked Clearsy model, needs:
seq - Some sequence functions (++ for example) are not implemented, but they are not used in this model.
logic - Clearsy model only uses quantifiers in invariants.
pattern match
- let - Clearsy model only uses simplest version let var = ...  Has implication for cases below.
- cases
  for seq + index
  call on object

**Comment by bandurvp** [comment]
This is a very old issue, all the relevant information is now contained in the Overture User Manual.
