### ISSUE TITLE
Name mangling incorrect

### ISSUE THREAD

**Issue by nlmave** [overturetool/vdm2c#25]
vdm2c/core/vdm2c/src/main/java/org/overture/codegen/vdm2c/utils/NameMangler.java

The patterns for seqId, setId and mapId seem incomplete and need an addition "%s" pattern postfix

**Comment by peterwvj** [comment]
I added unit tests for all the constructs that are mangled, and identified several other issues with the name mangler -- all of which have been fixed by now. In addition to the issues reported above, mangling of union types, `nat1`, `rat`,  `void`, `set1` and `seq1` was also fixed.
