### ISSUE TITLE
Let Expressions

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#3]
We have chosen to use the following C GNU construct to implement let-expressions: `({exp;stm;exp;})` https://gcc.gnu.org/onlinedocs/gcc/Statement-Exprs.html#Statement-Exprs

This allows a statement to occur as an expression. It will return the value of the last expression in the scope.

There is an alternative way to implement this using functions. However we chose the above simple solution of now but the function approach can be implement but requires some context searching for identifiers in scope.

**Comment by nickbattle** [comment]
So how does PJ do it in Java? (Not that Java matters, but why isn't the same approach possible?)

**Comment by peterwvj** [comment]
When I generate `let` expressions I assume that they occur in a statement context. Therefore, the Java code generator currently does not support 

```
values
x = let y = 1 in y;
```

What I really need to do is to initialize the corresponding Java fields using utility methods.

**Comment by peterwvj** [comment]
This issue seems mostly to be describing a design-choice and not an issue as such. Is there some place appropriate to document this other than the Github tracker, @bandurvp? If so, I would prefer to do that so we can close this issue.

**Comment by bandurvp** [comment]
Yes, as a design decision I think the best place to document this is in the CG deliverable.

**Comment by bandurvp** [comment]
I am closing this issue since it does not look as if "let" expressions are currently being generated as ({exp;stm;exp;}) constructs.
