### ISSUE TITLE
Ensure that google tests are generated and run

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#32]
The tests that exercise the generated code need to be updated to ensure that the googletests are run. To do this, two things must be done:
- [x] 1.The tests must be updated to generate an XML file that contains the test report
- [x] 2. The XML file must be inspected, for example using XPath, to ensure that the tests are run

@bandurvp : if you take care of the first task, then I'll take care of the second one.

**Comment by bandurvp** [comment]
I'll do the first one.

**Comment by bandurvp** [comment]
The basic starting point for item 2 would be something like this:
grep 'testsuites.*tests=' report.xml | awk '{print $2}'
Let me know if you want to build the inspection script for this together.

**Comment by peterwvj** [comment]
Great Victor, thanks.

Regarding item 2, I'll just use XPath (Java) to scan the document structure. My plan is to add it as a post  step for each of the unit tests, using JUnits "[at]After" annotation.

**Comment by peterwvj** [comment]
There still exists some tests that only check that the generated code compiles. Obviously this is not ideal, and eventually we should try to have all the tests execute the generated code. Therefore, I changed the test system to require that the test report (the XML file) must list at least one test if the JUnit test uses a googletest cpp file.
