### ISSUE TITLE
Initialization functions for values are not being called in class constructor

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#34]
The functions "_class_name__const_init" must be called in class constructors so that "value" elements can be used.

There is a more basic test for "value"s, ClassValue, which does pass, but the reason for this is that the appropriate calls are inserted in the test file ClassValue_Tests.cpp itself.  This was probably a temporary move.  With these commented out the test fails.

**Comment by bandurvp** [comment]
@peterwvj I've assigned you to this because I think it's a very good way to see the connection between the Java side and the native library.  The functions that need to be called are already being emitted by the generator, all that is required is to emit a call right at the end of the class constructor.  So the part that builds the body of the constructor must be amended to also emit a call to the initialization function.  We can work on it together.

**Comment by bandurvp** [comment]
It is a bit more subtle than just adding the initializer call to the constructor.  Because values/statics can be used without creating an instance of a class, it's necessary to call the initializer elsewhere.  I propose this strategy:  1)  The call is made in the constructor anyway, for those cases when an instance of the class does exist.  2)  Wherever a "value" or "static" field is accessed, the access is guarded by something like

if(static_or_value == NULL)
{
  call_initializer
}

If the value (which is a global called "g_ClassName_VarName") is NULL then the initializer has not been called yet, so it's legit to call it here.  In this way it's not necessary to force the user conventionally to call the initializers in the main function when he/she creates it.

The corresponding calls to g_ClassName_static_shutdown and g_ClassName_const_shutdown have to be inserted in the body of ClassName_free_fields.

**Comment by peterwvj** [comment]
Based on a discussion we had we agree that the best approach for now is to manually call the static initialisation/de-initialisation functions. Of course this information needs to be described in the user manual.
