### ISSUE TITLE
native lib is not copied/installed when generating code

### ISSUE THREAD

**Issue by nlmave** [overturetool/vdm2c#38]
When running the code generator in Overture 2.4.2 with vdm2c version 0.0.6 the nativelib directory is created when generating code but it remains empty.

**Comment by peterwvj** [comment]
This is fixed in 0.0.8 we simply forgot to close the issue. Can you confirm this?

**Comment by nlmave** [comment]
> This is fixed in 0.0.8 we simply forgot to close the issue. Can you
> confirm this?

No, it doesn't work in 2.4.2/0.0.8 on Windows7. nativelib directory is 
created but remains empty.

**Comment by peterwvj** [comment]
I added a fix for this issue. I can confirm that the native lib is now copied correctly on both Windows and Linux. The fix will ship with the next release of VDM2C. Alternatively, if you want to try it now, you can install one of the development versions of VDM2C, for example http://overture.au.dk/vdm2c/pvj/development/repository/
