### ISSUE TITLE
Transformations

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#39]
| Id | Input......................... | Output | Comment |
| --: | :-- | :-- | :-- |
| 1 | `values a: A` | `a_const_init; a_const_deinit` | Handled by `CreateGlobalConstInitFunctionTrans` |
| 2 | `static a: A` | `a_static_init; a_static_deinit` | Handled by `CreateGlobalStaticInitFunctionTrans` |
| 3 | `a: A` | a-constructor, destructor | Handled by the class template |
| 4 | `op(a,b,c())` | `apply_6(dcl a':? :=a);` <br> `apply_6(dcl b':? :=b);` <br>`apply_6(dcl c':? :=c());` <br> `op(a',b',c');` <br> `free(a',b',c')` |  |
| 5 | `x:= <exp>` | `apply( dcl x': ? :=nil;)` <br> `{ x' = apply(<exp>) }` <br> `free(x)` <br> `x = clone(x')` |  |
| 6 | `dcl x : T := <exp>` | `TVP x=NULL;` + apply_5(`x:=<exp>`) | separate declarations from assignments |
| 7 | `dcl x : T; stmts` | `TVP x; stmts;` at exit point `free(x)` <br>  iff last statement is different from `return x` | exit point is at `return` or at block end |
| 8 | `<literal-bool>` | `newBool(<literal-bool>)` |  |
| 8 | `<literal-int>` | `newInt(<literal-int>)` |  |
| 8 | `<literal-real>` | `newReal(<literal-real>)` |  |
| 8 | `<literal-char>` | `newChar(<literal-char>)` |  |
| 9 | `if <exp> then <stm1> else <stm2>` | `apply_7(dcl check:bool := <exp>)` <br> `if( boolValue(check ))` <br> `apply(<stm1>)` <br> `else` <br> `apply(<stm2>)` |  |

Open questions:

What about expressions on the form `a.op1().op2().op3()`.

**Comment by bandurvp** [comment]
No further plans to support the explicit approach to managing memroy.
