### ISSUE TITLE
Add support for basic map operations

### ISSUE THREAD

**Issue by miranha** [overturetool/vdm2c#44]
Add support for the most commonly used map operations:
- [X] Domain, e.g. `dom m`
- [X] Range, e.g. `rng m`
- [X] Map union e.g., `m1 munion m2`
- [X] Map apply e.g. `m(key)`
- [X] Map inverse, e.g. `inverse m`
- [X] Map equality, e.g. `m1 = m2`
- [X] Map inequality, e.g. `m1 <> m2`

**Comment by peterwvj** [comment]
I updated the issue to specifically describe what map operations the code generator supports
