### ISSUE TITLE
Add support for map comprehensions

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#47]
Do this after adding basic support for maps (see #44)

**Comment by peterwvj** [comment]
Currently, we don't really need this so we've decided not to implement this feature in the C code generator. Comprehensions are available for sequences and sets though.

**Comment by peterwvj** [comment]
After studying the Overture examples I found that the CashDispenser example (VDM++) is a suitable example to use in the paper, the reason being that this model uses a recursive function to analyse transactions.  The model happens to use map comprehensions, which is why I'm re-opening this issue.

**Comment by peterwvj** [comment]
@bandurvp , map comprehensions use `vdmMapGrow` and `vdmMapFit`, but these functions don't have GC counterparts in the runtime. Can you confirm that this is OK?

**Comment by bandurvp** [comment]
Hi Peter, that's right, these don't need GC versions.

**Comment by peterwvj** [comment]
Great, then we can consider this issue closed.
