### ISSUE TITLE
`CALL_*` from `VdmClass` contains undefined behaviour - avrgcc does not generate an useful implementation

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#50]
The basic problem with `CALL_FUN` is that it uses a loop up table where functions has a type like:

```C
TVP func(void*,...);
```

 A typical function could look like:

```C
TVP setValve(SensorCLASS this, TVP value);
```

this is then stored in the `vtable`
```C
{0,0,(VirtualFunctionPtr)setValve}
```

even though it looks ok the winavr compiler thinks otherwise to I think we must hit undefined behaviour. See this explanation for a good candidate for where the behaviour could be undefined in this case: http://stackoverflow.com/questions/559581/casting-a-function-pointer-to-another-type

Essentially we have a type:

```C
//the virtual ptr 
TVP (*)(void*,...)
// the actual type
TVP (*)(SensorCLASS this, TVP value)
```
I'm not sure about how to deal with the VARGS in this context but it looks like it could be undefined behaviour unless we cast it back to the original type again.

>The behavior is undefined in the following circumstances:
> * A pointer is used to call a function whose type is not compatible with the pointed-to type (6.3.2.3).

> **Section 6.3.2.3:** A pointer to a function of one type may be converted to a pointer to a function of another type and back again; the result shall compare equal to the original pointer. If a converted pointer is used to call a function whose type is not compatible with the pointed-to type, the behavior is undefined.

>The definition of compatible is somewhat complicated. It can be found in section 6.7.5.3, paragraph 15:
>For two function types to be compatible, both shall specify compatible return types127.
>
>Moreover, the parameter type lists, if both are present, shall agree in the number of parameters and in use of the ellipsis terminator; corresponding parameters shall have compatible types. If one type has a parameter type list and the other type is specified by a function declarator that is not part of a function definition and that contains an empty identifier list, the parameter list shall not have an ellipsis terminator and the type of each parameter shall be compatible with the type that results from the application of the default argument promotions. If one type has a parameter type list and the other type is specified by a function definition that contains a (possibly empty) identifier list, both shall agree in the number of parameters, and the type of each prototype parameter shall be compatible with the type that results from the application of the default argument promotions to the type of the corresponding identifier. (In the determination of type compatibility and of a composite type, each parameter declared with function or array type is taken as having the adjusted type and each parameter declared with qualified type is taken as having the unqualified version of its declared type.)
>
>127) If both function types are ‘‘old style’’, parameter types are not compared.

>**The relevant rule here is in section 6.7.5.1, paragraph 2:**
> For two pointer types to be compatible, both shall be identically qualified and both shall be pointers to compatible types.

**Comment by lausdahl** [comment]
The function call macro is defined as: 

``` C
/*
 * Macro to obtain a function from a (sub-)class specific VTable from a class struct
 */
#define CALL_FUNC(thisTypeName,funcTname,classValue,id, args... )     GET_VTABLE_FUNC( thisTypeName,funcTname,TO_CLASS_PTR(classValue,thisTypeName),id)(CLASS_CAST(TO_CLASS_PTR(classValue,thisTypeName),thisTypeName,funcTname), ## args)
```

This means that we could cast back the function ptr before invoking it:

``` C
/*
 * Macro to obtain a function from a (sub-)class specific VTable from a class struct
 */
#define CALL_FUNC(thisTypeName,funcTname,classValue,id, args... )  (CREATE_CALL_VARG_CAST(## args)   GET_VTABLE_FUNC( thisTypeName,funcTname,TO_CLASS_PTR(classValue,thisTypeName),id)  )(CLASS_CAST(TO_CLASS_PTR(classValue,thisTypeName),thisTypeName,funcTname), ## args)
```

By defining a macro that expands the vargs into a matching function type. This should be possible since we have everything we need: The type of `this` and the argument list from VARGS.

Here is a solution which constructs a `void*` cast e.g. it does not use the `this` type:

``` C
// Make a FOREACH macro
#define TVP_VARG_CAST_FE_1(WHAT, X) WHAT(X)
#define TVP_VARG_CAST_FE_2(WHAT, X, ...) WHAT(X)TVP_VARG_CAST_FE_1(WHAT, __VA_ARGS__)
#define TVP_VARG_CAST_FE_3(WHAT, X, ...) WHAT(X)TVP_VARG_CAST_FE_2(WHAT, __VA_ARGS__)
#define TVP_VARG_CAST_FE_4(WHAT, X, ...) WHAT(X)TVP_VARG_CAST_FE_3(WHAT, __VA_ARGS__)
#define TVP_VARG_CAST_FE_5(WHAT, X, ...) WHAT(X)TVP_VARG_CAST_FE_4(WHAT, __VA_ARGS__)
//... repeat as needed

#define TVP_VARG_CAST_GET_MACRO(_1,_2,_3,_4,_5,NAME,...) NAME
#define TVP_VARG_CAST_FOR_EACH(action,...) \
  TVP_VARG_CAST_GET_MACRO(__VA_ARGS__,TVP_VARG_CAST_FE_5,TVP_VARG_CAST_FE_4,TVP_VARG_CAST_FE_3,TVP_VARG_CAST_FE_2,TVP_VARG_CAST_FE_1)(action,__VA_ARGS__)

#define TVP_VARG_CAST_ARG_TYPE(N) , TVP
#define CREATE_CALL_VARG_CAST(...) TVP (*)(void*TVP_VARG_CAST_FOR_EACH(TVP_VARG_CAST_ARG_TYPE,__VA_ARGS__))
```

note that this implementation can expand 5 arguments but it can be extended to at least 60 do not remember the max but this is more that what is good design in VDM anyway. Solution inspired by http://stackoverflow.com/questions/1872220/is-it-possible-to-iterate-over-arguments-in-variadic-macros

**Comment by lausdahl** [comment]
I think this illustrate it:

``` C
#define TVP int

int add(void* self, int a, int b)
{
    printf("Called with %d and %d\n",a,b);
    return 0;
}

int main(void)
{
    printf("Calling\n");

    //cast to wrong type
    int (*f)(int) = &add;

    //cast it back before invoking it
    ((CREATE_CALL_VARG_CAST(1,1))f)(0,1,4);

    return 0;
}
```

the expanded version look like:

``` C
int main(void)
{
 printf("Called\n");
 int (*f)(int) = &add;


 ((int (*)(void*, int, int))f)(0,1,4);

 return 0;
}
```

and since that standard says that we can temporary have to pointer stored in a "wrong" type it is ok if we cast it back before we use it. "wrong" refers to the fact that some types are smaller and cannot hold the function pointer so this excludes these.

@bandurvp lets give this a try when we get the JTAG again

**Comment by lausdahl** [comment]
Note about `, ## _VA_ARGS__` https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

**Comment by bandurvp** [comment]
Hey Kenneth, I see what you've done here.  So what was the status when you left it?

**Comment by lausdahl** [comment]
I fixed this but it uses a  `void*` and not the actual struct type which is known to the call macro. So I think we need to check if `struct X*` and `void*` is considered equal in the C standard. If not we need to modify the macro `TVP_VARG_CAST_FE_1` to also take the struct type.
