### ISSUE TITLE
Wrong behaviour when compiled to ATMega1284P

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#52]
If the code is compiled with optimisation `-O2` then it seem to break the generated code. Calls and variables does not work and have bad values.

http://www.avrfreaks.net/forum/avr-gcc-optimization-bug-reported-newbie

This could also be a side effect of #50 and #51

**Comment by bandurvp** [comment]
Commit 8890910421eb6c283cea3a058dde58148a120a90 works with optimization level -O3.
