### ISSUE TITLE
Profile memory usage on ATMega1284P

### ISSUE THREAD

**Issue by lausdahl** [overturetool/vdm2c#53]
* Driver for the UART: http://www.avrfreaks.net/forum/atmega1284p-simple-serial
* http://stackoverflow.com/questions/960389/how-can-i-visualise-the-memory-sram-usage-of-an-avr-program
* http://www.nongnu.org/avr-libc/user-manual/malloc.html

**Comment by bandurvp** [comment]
With latest version of FMU exporter and VDM2C, RAM usage is constant as of 8890910421eb6c283cea3a058dde58148a120a90.
