### ISSUE TITLE
Incorrect reference to unused subclass

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#59]
The FCU INTO-CPS case study at https://github.com/into-cps/case-study_fcu contains a sub-class `MechanicalController` that is not used in the rest of the model.  When the model is generated, the constructor `_Z6SystemEV` in file `System.c` contains lines like

`TVP field_tmp_19 = vdmClone(_Z15ActuatorLimitedE8CRealPort(NULL, GET_FIELD(MechanicalController, MechanicalController, vdmClone(g_System_hwi), valveOpen)));`

when they should actually be

`TVP field_tmp_19 = vdmClone(_Z15ActuatorLimitedE8CRealPort(NULL, GET_FIELD(HardwareInterface, HardwareInterface, vdmClone(g_System_hwi), valveOpen)));`

The class in question is a sub-class of `Controller`, and the file `System.c` does not `#include` `MechanicalController.h`.  When `MechanicalController.vdmrt` is deleted the generated code looks fine and compiles.

**Comment by peterwvj** [comment]
I'm not sure I entirely understand this issue. Does it have to do with the `HardwareInterface` or is that unrelated?

The VDM-RT model that I can find in the FCU repository is quite large. Can this issue be demonstrated using a much smaller example? Preferably one that does not use the `HardwareInteface`.

**Comment by bandurvp** [comment]
Hi Peter, I have tried to make a minimal example with no success.  Then I tried growing the example where it is essentially the same as the initial model, but with everything else removed, but this also does not reveal the problem.  The example I have now has all the required classes, but in a single file.

**Comment by bandurvp** [comment]
Hi Peter,

I've pared down the model to that included below.  It seems the problem has to do with variables in different classes having the same name.  It has nothing to do with inheritance as I initially thought.  There is a comment on the variable in question below.


[System-vdmrt.txt](https://github.com/overturetool/vdm2c/files/701817/System-vdmrt.txt)

**Comment by bandurvp** [comment]
A simplification to the file above:

```
class A

instance variables

  public fanSpeed : int := 0;
  
end A



class B
     
instance variables

	--  If this variable is renamed the generated code is correct.
	fanSpeed : int;
	
end B



class C

instance variables
	
  public static hwi: A := new A();  
  fan : int;
  	
operations

public C : () ==> C
C () == 
(
	fan := hwi.fanSpeed;
);

end C
```
