### ISSUE TITLE
Case study models for compilation regression testing

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#61]
Include the following models for compilation regression testing.

- [x] Single water tank pilot study found at into-cps/case-study_single_water_tank/Models/SingleWT
 - https://github.com/into-cps/case-study_single_watertank

- [x] Three water tank pilot study found at into-cps/case-study_three_tank/Models/WaterTankController
- https://github.com/into-cps/case-study_three_tank

- [x] Line follower robot pilot study found at into-cps/case-study_line_follwer_robot/Models/LFRController
- https://github.com/into-cps/case-study_line_follower_robot

- [x] UTRC year 1 Fan Coil Unit case study found at into-cps/case-study_fcu/Models/FCUController
 - https://github.com/into-cps/case-study_fcu

**Comment by peterwvj** [comment]
Very good. I'll work on this some time next week.

**Comment by peterwvj** [comment]
Hi @bandurvp. I was looking for the case studies in the INTO-CPS SVN repository but I couldn't find them. Could you please provide me with a direct URL (perhaps by sending it to me by email)? Are they stored somewhere else? Thanks!

**Comment by bandurvp** [comment]
Hi Peter,

I meant in the into-cps GitHub project.

Victor

**Comment by peterwvj** [comment]
Oh.. You're right. The case study models exist as individual GIthub repositories under the [INTO-CPS organisation](https://github.com/into-cps). Thanks.

**Comment by bandurvp** [comment]
That's right, I'm sorry I should have been clearer about it.  They're maintained like this because it plays well with the INTO-CPS App, where projects are stored as GitHub projects.

**Comment by peterwvj** [comment]
@bandurvp @miranha 

The case study models listed above are now included as submodules in the main repository. So make sure you run `git submodule update --init` after you merge `pvj/gc`. In addition, I've set up a unit tests that performs compilation regression testing for each of these models.

Should we add additional models for testing?

**Comment by peterwvj** [comment]
I should say that currently the case study models are only tested using VDM2C/GC.
