### ISSUE TITLE
Reduce the size of the runtime library

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#72]
The plan is to reduce the runtime library using condition compilation. For example, if a model does not use sets then it does not need the corresponding part of the runtime library. Currently, we'll check if the model uses the following VDM features:

- [x] sets
- [x] sequences
- [x] maps
- [x] patterns (unless it's identifier patterns)
- [x] products
- [x] records
- [x] uses garbage collection
- [x] MATH library
- [x] CSV library
- [x] IO library
- [x] VDMUtil library
- [x] VDMUnit (and all it's utility classes, e.g. `Assert`)
- etc.

This list is subject to change (feel free to extend or modify it).

Based on this analysis, the C code generator will emit a C file that contains flags that indicates whether some language feature or library is used. The names of the flags are as follows:

* NO_SETS
* NO_SEQS
* NO_MAPS
* NO_PATTERNS
* NO_PRODUCTS
* NO_RECORDS
* NO_GC
* NO_MATH
* NO_CSV
* NO_IO
* NO_VDMUTIL
* NO_VDMUNIT

The name of the output file must be `VdmModelFeatures.h`.

**Comment by peterwvj** [comment]
@bandurvp The FMU exporter would not something like this:
https://github.com/overturetool/vdm2c/blob/pvj/gc/ide/cgen/src/main/java/org/overture/ide/plugins/cgen/generator/CGenerator.java#L83

**Comment by bandurvp** [comment]
Tests were excluded from the runtime library based on the ```VdmModelFeatures.h``` file in comit 6b72d34bdf740d5a4fe04bb6418b2d375a1d62fe.

**Comment by bandurvp** [comment]
Pattern matching was excluded from the runtime library based on the ```VdmModelFeatures.h``` file in commit a0c22b34598c8f26e0c956ce421a8c46d9f9fdc3.

**Comment by bandurvp** [comment]
Dependency graph for ```VdmModelFeatures.h``` file:  ```Maps --uses--> Sets``` and ```Seqs --uses--> Sets```.

A note on reducing the size of the runtime based on NO_SETS:  for maps it is currently impossible to eliminate map operations that use sets when NO_SETS is specified because the implementations of many of the map operations that do *not* rely on sets in their signatures themselves use sets.

**Comment by bandurvp** [comment]
@peterwvj , I think we can eliminate NO_VDMUNIT from this effort.  There is no corresponding implementation in the runtime and there is no plan to support VDM unit testing.
