### ISSUE TITLE
Generated code to contain the version number of the generator.

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#73]
Not yet sure where the best place for this would be, need to discuss.

**Comment by peterwvj** [comment]
That's a good idea. We could add it as a comment in every file that is generated, i.e. the header files, the .c files and the model features file. Am I missing some? We could add something like that shown below, but if you have another suggestion then I'm happy to use that.

```C
/**
* This file is generated by Overture's VDM-to-C code generator version <version>.
* Website: https://github.com/overturetool/vdm2c
*/
```

**Comment by bandurvp** [comment]
Sounds good.  I'm thinking of how to get the same information into the static runtime files.  If you have a good idea let me know!

Victor

**Comment by peterwvj** [comment]
It is possible, using some Maven plugin, to perform a `sed`-like function. If that works well, we could use this approach to update version numbers as part of the release process.. but I would have to look into this before I can say for certain that this is a viable solution.

**Comment by bandurvp** [comment]
That's the sort of thing I had in mind as well, insert the version number via some sort of sed replace after everything is in place.  I can write the sed stuff if we go ahead with this.

Victor

**Comment by peterwvj** [comment]
Inspired by [this](http://stackoverflow.com/questions/3697449/retrieve-version-from-maven-pom-xml-in-code) and [this](http://stackoverflow.com/questions/8764500/programmatically-getting-the-maven-version-of-your-project), I've updated the code generator to emit the above comment in the following files:

- main.c
- MangledNames.h
- VdmModelFeatures.h
- header files (.h) and C sources (.c) that represent VDM classes

This approach, however, will not work for the static runtime files so we need to use a "replace" plugin for those files. I'll look into this tomorrow.

I've pushed this changed to pvj/development. @bandurvp, could you try it out when you have a minute?

**Comment by bandurvp** [comment]
Works well on my end.  Regarding the main.c file, you're referring to the one that's output when CG is invoked from the menu in Overture, right?

Victor

**Comment by peterwvj** [comment]
Good! Yes, the one that is emitted by Overture.

**Comment by bandurvp** [comment]
The rest of the (non-generated) runtime library files should contain the following note at the top:  "VERSION:  For the version of VDM2C used to generate this project, refer to one of the generated files."
