### ISSUE TITLE
Range information for quote types

### ISSUE THREAD

**Issue by miranha** [overturetool/vdm2c#76]
The distributed code generator needs to be able to associate a given quote type element with its type as defined under the ```types``` clause.  The idea is three-fold.

1. Change the name of quote ```#define```s from ```QUOTE_<literal_name>``` to ```<QuoteTypeName>_<literal_name>```.  This allows the generator to handle the case of overlapping quote literal names, as shown in the model below.

2. Have the generator generate unique sequential numbers for every element of all quote types found in a model.  For instance, a model defining
```
types
   QuoteType1 = <Q1> | <Q2>;
   QuoteType2 = <Q1> | <Q2> | <Q3>;
```
should generate quote defines as follows:
```
#define QuoteType1_Q1 1
#define QuoteType1_Q2 2

#define QuoteType2_Q1 5
#define QuoteType2_Q2 6
#define QuoteType2_Q3 7
```
Currently the numbers are the hash values of the strings corresponding to the quote literals Q1, Q2 etc.  The numbers themselves do not matter, as long as they are sequential.

3. For each quote type encountered, the generator must emit ```#define```s stating the min and max of their values.  For the above, this means emitting the following:
```
#define QuoteType1_MIN 1
#define QuoteType1_MAX 2

#define QuoteType2_MIN 5
#define QuoteType2_MAX 7
```

**Comment by bandurvp** [comment]
@peterwvj I originally assigned myself to this thinking that it would be a quick job for me, but it's more involved than I imagined, requiring your expertise!

**Comment by peterwvj** [comment]
I may misunderstand what this issue is really about, but to make it clear: quote types do not have to appear in a `types` clause before they can be used. Think of a quote type `<A>` as a type that only has a single value, namely `<A>`. To demonstrate, consider the following type-correct VDM class:

```
class A

values

v : <A> = <A>

functions

public f :  () -> <B>
f () ==
let b : <B> = <B>
in
  b;

end A
```
So perhaps we need to approach this in a different way? Can you try to clarify the problem we are really trying to solve? We most likely need to discuss this face-to-face :)

**Comment by miranha** [comment]
Yes, I agree face-to-face would be best. Victor and I also created this issue after we talked in person, so maybe it is not clear for others. Lets talk about this next week then.

**Comment by peterwvj** [comment]
Based on today's discussion the solution is to:

* Leave generated code as it
* Serialise quotes as integers
