### ISSUE TITLE
Many VDM test models missing corresponding CPP test files.

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#8]

**Comment by bandurvp** [comment]
Hi @peterwvj , in the beginning I think we started testing the runtime library by having parallel versions of tests, a VDM model of the test and a corresponding hand-written `.cpp` file.  I don't think we've followed this approach for a while now.  I would like to remove the folder `c/vdm` and close this issue.  Do you see anything wrong with this?

**Comment by peterwvj** [comment]
No, I fully support your suggestion.
