### ISSUE TITLE
Add support for tokens

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#80]
The Alarm example uses tokens, which we don't support. What to do?

- [x] add newToken(TVP v) + GC version in the runtime
  - The argument is a sequence of characters
- [x] update all relevant runtime functions
- [x] update  name mangler accordingly
- [x] Convert `mk_token(...)` expressions to apply expressions
- [x] update garbage collection transformation

**Comment by bandurvp** [comment]
Runtime library support available as of commit 112ebb91991748bb7dcf3acce6c5e93793ba3f66.

**Comment by peterwvj** [comment]
The token tests that I just added pass. Next step is to try it with the Alarm example.

**Comment by bandurvp** [comment]
Fantastic stuff!!

Victor
