### ISSUE TITLE
Add GC support for sequences

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#85]
From previous communication with @peterwvj : 

> For practical reason we might also want to add seqVarCG. The problem is that currently a string is treated as sequence of characters. For example, the VDM fragment v = "hi" is translated to TVP v = newSeqVar(2, newCharGC('h', NULL), newCharGC('i', NULL)), which the garbage collector currently cannot handle.

**Comment by bandurvp** [comment]
The signature of ```newSeqVar()``` is ```TVP newSeqVarGC(size_t size, ...)```.  I am thinking of putting the ```from``` parameter before the list of arguments, as such:  ```TVP newSeqVarGC(size_t size, TVP *from, ...)```.  Is this OK from the point of view of the Java side, @peterwvj ?

**Comment by peterwvj** [comment]
Sure! I'll just handle it as a special case in the garbage collection transformation :) It should not be a problem.

**Comment by bandurvp** [comment]
Added in commit 1bac2398465603ef9b60ad173729a09d014e53ec.
