### ISSUE TITLE
Finalise pretty-printer function

### ISSUE THREAD

**Issue by peterwvj** [overturetool/vdm2c#88]
There is already some work on a TVP pretty-printer function in PrettyPrinter.c. We need to finalise this function as we need it to test the alarm example. Also, ensure that the top-level function is called "toString" rather than "printVdmBasicValue".

**Comment by bandurvp** [comment]
According to our discussion today, @peterwvj , I'll postpone working on this any further.  At the moment I don't see an economical way of carrying around the names of classes and records, so it does not make good sense to clutter the binary.
