### ISSUE TITLE
Exercise plan for AlarmPP model

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#89]
Devise an exercise plan, written in VDM, that exercises execution time and memory usage.  This night be split up into:

1. A validation plan, that ensures that the generated model behaves as it should.
2. A (potentially independent) exercise plan.

**Comment by bandurvp** [comment]
I have discovered a useful feature of VDMTools.  Basic values at least, such as ```bool```, can be pretty-printed in the usual C++ way ```cout << var;```.  I have used this in the validation plan to confirm that the VDMTools generated code works as expected.

**Comment by peterwvj** [comment]
Cool. I actually thought we tested that -- perhaps we only tried it on user-defined data types :)

**Comment by bandurvp** [comment]
An update, an initial stress test runs correctly and without memory leaks.  The test model code is in the SVN in the WellFoundedCG paper folder.

**Comment by bandurvp** [comment]
@peterwvj , I'm very happy to report that the first test, that in which I check whether the generated code actually performs correctly, shows code from VDM2C to use almost half the total memory that code from VDMTools does!

**Comment by peterwvj** [comment]
Awesome, Victor :) That's very promising. Thanks for letting me know!

**Comment by peterwvj** [comment]
I think this can be closed now.
