### ISSUE TITLE
Make exported code C99 compliant

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#91]
This description to be updated soon with what specific constructs must be changed.

**Comment by peterwvj** [comment]
Victor, if 651566093f1570020f60d06de4c12bc53e445ad5 forces C99 for all the generator tests does this not imply that we're already C99 compliant? I mean, the tests pass.

**Comment by bandurvp** [comment]
Hi @peterwvj, yes that's right.  So we're good for C99, at least as far as the tests go.  I'm now working on C89 compliance, which is a bit more strict.  But so far it only has to do with comments and not with any constructs emitted by the generator.

**Comment by peterwvj** [comment]
Sounds good, Victor.

**Comment by bandurvp** [comment]
In this case I'll close this one and open another for C89.
