### ISSUE TITLE
Investigate Maven test hanging when compilation of test code fails

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#92]
The file to change is ```core/src/test/resources/CMakeLists.txt```.  Thange ```-std=c11``` to ```-std=c89``` in the following block:
```
IF(CMAKE_COMPILER_IS_GNUCC)
  SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fmessage-length=0 -std=c11")
ENDIF(CMAKE_COMPILER_IS_GNUCC)
IF(CMAKE_COMPILER_IS_GNUCXX)
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fmessage-length=0")
ENDIF(CMAKE_COMPILER_IS_GNUCXX)
```
On my machine ```CasesTest``` hangs via ```mvn clean install```, but the actual problem is that the compilation fails.

**Comment by peterwvj** [comment]
@bandurvp I just tried to run all tests with `-std=c89` and although most of them fail due to the conformance check, none of them seem to hang. Is this a problem you can reproduce?

**Comment by bandurvp** [comment]
Hi @peterwvj , I can't reproduce it any longer, it might have been a transient thing on my computer.  Let's just leave it alone.

**Comment by peterwvj** [comment]
Good, thanks for following up.
