### ISSUE TITLE
Make exported code C89 compliant

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#93]
So far the only non-conformant examples I see in the code are instances of 
```
for(TVP iterator_1 = ...)
```
For C89 conformance the declaration of ```iterator_1``` must be done before:
```
TVP iterator_1;
for(iterator_1 = ...)
```
I've changed all these in the runtime library, what remains comes from the generator, so I'll only assign this to you @peterwvj .

**Comment by peterwvj** [comment]
Good, I'll take care of that.

**Comment by bandurvp** [comment]
Very nice!  Then we'll be all set for the CLP guys and their method of deploying the generated code automatically to embedded platforms.  We should release at that point.

**Comment by peterwvj** [comment]
Like you said, it was only a matter of converting all the for loops into C89 compliant ones. The generated code is now C89 compliant.
