### ISSUE TITLE
Header file not getting included

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#98]
Hi @peterwvj , when the following model is generated,
```
class A
instance variables

	public static done: bool := false
end A



class B
operations
public Step: () ==> ()
Step() ==
	if time >= 0 then A`done := true
end B
```
```B.h``` does not contain an ```#include "A.h"``` directive.

**Comment by peterwvj** [comment]
Thanks for the bug report. I'll take a look when I have a minute.

**Comment by peterwvj** [comment]
@bandurvp Can you confirm that the fix works as expected?

**Comment by bandurvp** [comment]
Hi Peter, it works, thanks!  What was it?

**Comment by peterwvj** [comment]
There's a transformation that computes the header files that each class depends on. That transformation did not consider identifier state designators so I simply had to add that case  ☺️

**Comment by bandurvp** [comment]
I thought it might be something like that, from the way the transformations work.  Excellent progress!
