### ISSUE TITLE
Names of omitted classes included in #include directives in main.c file

### ISSUE THREAD

**Issue by bandurvp** [overturetool/vdm2c#99]
When generating a VDM-RT project that contains only the VDM IO and Unit libraries, ```#include``` directives corresponding to omitted classes ```Throwable```, ```TestCase``` etc. are included in the main file emitted when the generator is invoked form inside Overture.  The function that emits the ```main.c``` file is ```emitMainFile``` in ```CGenerator.java```.  Currently this is not a smart implementation, and should rather take into account the list of header files actually produced.  The relevant part of the ```main.c``` file is:
```
#include "IO.h"
#include "Throwable.h"
#include "Error.h"
#include "AssertionFailedError.h"
#include "Assert.h"
#include "Test.h"
#include "TestCase.h"
#include "TestSuite.h"
#include "TestListener.h"
#include "TestResult.h"
#include "TestRunner.h"
```

**Comment by peterwvj** [comment]
@bandurvp I need you to help me understand exactly which header files must be included. Is it sufficient to only consider user-defined once (and omit the library headers)?
